const students = [
    {
        id: 1,
        name: "Sarthak Kumar",
        enrollmentNumber: "0191CS231234",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436544/Sarthak-Kumar_fpzqde.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 2,
        name: "Mohd Meraaz",
        enrollmentNumber: "0191AL221090",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436557/Mohd-Meraaz_r9nh6n.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 3,
        name: "Siddharth Kumar",
        enrollmentNumber: "0192CS231193",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436547/Siddharth-Kumar_tuxfyc.jpg",
        skills: ["Android"],
    },
    {
        id: 4,
        name: "Aryan Sharma",
        enrollmentNumber: "0192CS231051",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436536/Aryan_llmi2k.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 5,
        name: "Nikhil Kumar Gupta",
        enrollmentNumber: "0191CS231171",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436542/Nikhil-Kumar-gupta_aqtqlx.jpg",
        skills: ["ML", "Cyber"],
    },
    {
        id: 6,
        name: "Rishabh Raj",
        enrollmentNumber: "0111T231100",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436543/Rishabh-Raj_ti68wc.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 7,
        name: "Naman Kumar",
        enrollmentNumber: "0191CS231137",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436552/Naman-Kumar_bmlngv.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 8,
        name: "Rohit Tiwari",
        enrollmentNumber: "0111CS231111",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436543/Rohit-Tiwari_pwhjkt.jpg",
        skills: ["ML", "Web Dev"],
    },
    {
        id: 9,
        name: "Om Prakash Mehta",
        enrollmentNumber: "0191CS231177",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436542/Om-Prakash_si22kt.png",
        skills: ["Cyber"],
    },
    {
        id: 10,
        name: "Shashank Kumar",
        enrollmentNumber: "0111AL231244",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436546/Shashank-Agrawal_ohm4kc.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 11,
        name: "Anikesh Sharma",
        enrollmentNumber: "0191CS231044",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436540/Anikesh-Sharma_otngh4.png",
        skills: ["ML"],
    },
    {
        id: 12,
        name: "Sheetal Kawadkar",
        enrollmentNumber: "0191AL221162",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436547/Sheetal-Kawadkar_vyrj80.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 13,
        name: "Dipu Kumar",
        enrollmentNumber: "0191CS231111",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436540/Dipu-Kumar_aoq859.png",
        skills: ["Cyber", "Android"],
    },
    {
        id: 14,
        name: "Shaloni Mishra",
        enrollmentNumber: "0191AL221160",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436546/shaloni-mishra_irpldl.jpg",
        skills: ["ML", "Web Dev"],
    },
    {
        id: 15,
        name: "Aditi Gupta",
        enrollmentNumber: "0192CS221010",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436534/Aditi-Gupta_y1jaw5.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 16,
        name: "Neetesh Chaurasia",
        enrollmentNumber: "0111A231075",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436541/Neetesh-Chaurasia_v7slff.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 17,
        name: "Prince Kumar",
        enrollmentNumber: "0191CS231198",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436543/Prince-Kumar_ibthcw.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 18,
        name: "Shivam Kumar Tiwari",
        enrollmentNumber: "0111CS231132",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436547/Shivam-Tiwari_b629wk.jpg",
        skills: ["ML", "Web Dev", "Cyber"],
    },
    {
        id: 19,
        name: "Harshit Anand",
        enrollmentNumber: "0191CS221090",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436554/Harshit-Anandd_epabbj.jpg",
        skills: ["Web Dev", "Cyber", "Android"],
    },
    {
        id: 20,
        name: "Akash Kumar",
        enrollmentNumber: "0191CS231029",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436535/Akash-Kumar_zoq1sk.jpg",
        skills: ["Cyber"],
    },
    {
        id: 21,
        name: "Ananya Gupta",
        enrollmentNumber: "0191AL221019",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436535/Ananya-Gupta_vdc2dn.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 22,
        name: "Yashraj Chouhan",
        enrollmentNumber: "0191AL221204",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436548/Yashraj-Chouhan_sk01zl.png",
        skills: ["Cyber"],
    },
    {
        id: 23,
        name: "Sejal Tiwari",
        enrollmentNumber: "1091CS231241",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436546/Sejal-Tiwari_xfhgyr.png",
        skills: ["ML", "Web Dev", "Cyber", "Android"],
    },
    {
        id: 24,
        name: "Aman Mishra",
        enrollmentNumber: "0191CS231034",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436540/Aman-Mishra_uougsv.jpg",
        skills: ["ML"],
    },
    {
        id: 25,
        name: "Prakhar Shrivastava",
        enrollmentNumber: "0191CS231189",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436545/Prakhar-Shrivastava_nv2qru.jpg",
        skills: ["ML", "Web Dev", "Cyber"],
    },
    {
        id: 26,
        name: "Deepika Deshmukh",
        enrollmentNumber: "0192AL221028",
        program: "Web Development, 2nd Year",
        image: "https://res.cloudinary.com/dltyctci9/image/upload/v1743436537/Deepika-Deshmukh_pddfvy.jpg",
        skills: ["ML", "Web Dev"],
    }
];



export default students;
