const students = [
    {
        id: 1,
        name: "Sarthak Kumar",
        enrollmentNumber: "0191CS231234",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Sarthak-Kumar.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 2,
        name: "Mohd Meraaz",
        enrollmentNumber: "0191AL221090",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Mohd-Meraaz.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 3,
        name: "Siddharth Kumar",
        enrollmentNumber: "0192CS231193",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Siddharth-Kumar.jpg",
        skills: ["Android"],
    },
    {
        id: 4,
        name: "Aryan Sharma",
        enrollmentNumber: "0192CS231051",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Aryan.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 5,
        name: "Nikhil Kumar Gupta",
        enrollmentNumber: "0191CS231171",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Nikhil-Kumar-gupta.jpg",
        skills: ["ML", "Cyber"],
    },
    {
        id: 6,
        name: "Rishabh Raj",
        enrollmentNumber: "0111T231100",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Rishabh-Raj.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 7,
        name: "Naman Kumar",
        enrollmentNumber: "0191CS231137",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Naman-Kumar.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 8,
        name: "Rohit Tiwari",
        enrollmentNumber: "0111CS231111",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Rohit-Tiwari.jpg",
        skills: ["ML", "Web Dev"],
    },
    {
        id: 9,
        name: "Om Prakash Mehta",
        enrollmentNumber: "0191CS231177",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Om-Prakash.png",
        skills: ["Cyber"],
    },
    {
        id: 10,
        name: "Shashank Kumar",
        enrollmentNumber: "0111AL231244",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Shashank-Agrawal.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 11,
        name: "Anikesh Sharma",
        enrollmentNumber: "0191CS231044",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Anikesh-Sharma.png",
        skills: ["ML"],
    },
    {
        id: 12,
        name: "Sheetal Kawadkar",
        enrollmentNumber: "0191AL221162",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Sheetal-Kawadkar.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 13,
        name: "Dipu Kumar",
        enrollmentNumber: "0191CS231111",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Dipu-Kumar.png",
        skills: ["Cyber", "Android"],
    },
    {
        id: 14,
        name: "Shaloni Mishra",
        enrollmentNumber: "0191AL221160",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/shaloni-mishra.jpg",
        skills: ["ML", "Web Dev"],
    },
    {
        id: 15,
        name: "Aditi Gupta",
        enrollmentNumber: "0192CS221010",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Aditi-Gupta.jpg",
        skills: ["Cyber", "Android"],
    },
    {
        id: 16,
        name: "Neetesh Chaurasia",
        enrollmentNumber: "0111A231075",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Neetesh-Chaurasia.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 17,
        name: "Prince Kumar",
        enrollmentNumber: "0191CS231198",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Prince-Kumar.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 18,
        name: "Shivam Kumar Tiwari",
        enrollmentNumber: "0111CS231132",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Shivam-Tiwari.jpg",
        skills: ["ML", "Web Dev", "Cyber"],
    },
    {
        id: 19,
        name: "Harshit Anand",
        enrollmentNumber: "0191CS221090",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Harshit-Anandd.jpg",
        skills: ["Web Dev", "Cyber", "Android"],
    },
    {
        id: 20,
        name: "Akash Kumar",
        enrollmentNumber: "0191CS231029",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Akash-Kumar.jpeg",
        skills: ["Cyber"],
    },
    {
        id: 21,
        name: "Ananya Gupta",
        enrollmentNumber: "0191AL221019",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Ananya-Gupta.jpg",
        skills: ["Web Dev"],
    },
    {
        id: 22,
        name: "Yashraj Chouhan",
        enrollmentNumber: "0191AL221204",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Yashraj-Chouhan.png",
        skills: ["Cyber"],
    },
    {
        id: 23,
        name: "Sejal Tiwari",
        enrollmentNumber: "1091CS231241",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Sejal-Tiwari.png",
        skills: ["ML", "Web Dev", "Cyber", "Android"],
    },
    {
        id: 24,
        name: "Aman Mishra",
        enrollmentNumber: "0191CS231034",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Aman-Mishra.jpg",
        skills: ["ML"],
    },
    {
        id: 25,
        name: "Prakhar Shrivastava",
        enrollmentNumber: "0191CS231189",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Prakhar-Shrivastava.jpg",
        skills: ["ML", "Web Dev", "Cyber"],
    },
    {
        id: 26,
        name: "Deepika Deshmukh",
        enrollmentNumber: "0192AL221028",
        program: "Web Development, 2nd Year",
        image: "/assets/img/testimonial-img/student-img/Deepika-Deshmukh.jpg",
        skills: ["ML", "Web Dev"],
    }
];



export default students;
